// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Organizzae.Infrastructure.Data.Context;

#nullable disable

namespace Organizzae.Infrastructure.Migrations
{
    [DbContext(typeof(OrganizzaeDbContext))]
    [Migration("20251218163946_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Organizzae.Domain.Entities.Categoria", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("Ativo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<string>("CorHexadecimal")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(7)
                        .HasColumnType("nvarchar(7)")
                        .HasDefaultValue("#6c757d");

                    b.Property<DateTime?>("DataAtualizacao")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DataCriacao")
                        .HasColumnType("datetime2");

                    b.Property<string>("Descricao")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<bool>("EhPadrao")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<string>("Icone")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("Tipo")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("EhPadrao")
                        .HasDatabaseName("IX_Categorias_EhPadrao");

                    b.HasIndex("Tipo")
                        .HasDatabaseName("IX_Categorias_Tipo");

                    b.HasIndex("Nome", "Tipo")
                        .HasDatabaseName("IX_Categorias_Nome_Tipo");

                    b.ToTable("Categorias", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("11111111-1111-1111-1111-111111111111"),
                            Ativo = true,
                            CorHexadecimal = "#FF6B6B",
                            DataCriacao = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Descricao = "Aluguel, condomínio, IPTU, manutenção",
                            EhPadrao = true,
                            Icone = "fa-home",
                            Nome = "Moradia",
                            Tipo = 1
                        },
                        new
                        {
                            Id = new Guid("22222222-2222-2222-2222-222222222222"),
                            Ativo = true,
                            CorHexadecimal = "#4ECDC4",
                            DataCriacao = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Descricao = "Supermercado, restaurantes, delivery",
                            EhPadrao = true,
                            Icone = "fa-utensils",
                            Nome = "Alimentação",
                            Tipo = 1
                        },
                        new
                        {
                            Id = new Guid("33333333-3333-3333-3333-333333333333"),
                            Ativo = true,
                            CorHexadecimal = "#FFE66D",
                            DataCriacao = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Descricao = "Combustível, transporte público, manutenção veículo",
                            EhPadrao = true,
                            Icone = "fa-car",
                            Nome = "Transporte",
                            Tipo = 1
                        },
                        new
                        {
                            Id = new Guid("44444444-4444-4444-4444-444444444444"),
                            Ativo = true,
                            CorHexadecimal = "#95E1D3",
                            DataCriacao = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Descricao = "Plano de saúde, medicamentos, consultas",
                            EhPadrao = true,
                            Icone = "fa-heartbeat",
                            Nome = "Saúde",
                            Tipo = 1
                        },
                        new
                        {
                            Id = new Guid("55555555-5555-5555-5555-555555555555"),
                            Ativo = true,
                            CorHexadecimal = "#A8E6CF",
                            DataCriacao = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Descricao = "Cursos, livros, mensalidade escolar",
                            EhPadrao = true,
                            Icone = "fa-graduation-cap",
                            Nome = "Educação",
                            Tipo = 1
                        },
                        new
                        {
                            Id = new Guid("66666666-6666-6666-6666-666666666666"),
                            Ativo = true,
                            CorHexadecimal = "#C7CEEA",
                            DataCriacao = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Descricao = "Cinema, viagens, hobbies",
                            EhPadrao = true,
                            Icone = "fa-gamepad",
                            Nome = "Lazer",
                            Tipo = 1
                        },
                        new
                        {
                            Id = new Guid("77777777-7777-7777-7777-777777777777"),
                            Ativo = true,
                            CorHexadecimal = "#FFDAC1",
                            DataCriacao = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Descricao = "Roupas, calçados, acessórios",
                            EhPadrao = true,
                            Icone = "fa-tshirt",
                            Nome = "Vestuário",
                            Tipo = 1
                        },
                        new
                        {
                            Id = new Guid("88888888-8888-8888-8888-888888888888"),
                            Ativo = true,
                            CorHexadecimal = "#B4A7D6",
                            DataCriacao = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Descricao = "Energia, água, internet, telefone",
                            EhPadrao = true,
                            Icone = "fa-file-invoice-dollar",
                            Nome = "Contas e Serviços",
                            Tipo = 1
                        },
                        new
                        {
                            Id = new Guid("99999999-9999-9999-9999-999999999999"),
                            Ativo = true,
                            CorHexadecimal = "#6C757D",
                            DataCriacao = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Descricao = "Despesas diversas",
                            EhPadrao = true,
                            Icone = "fa-ellipsis-h",
                            Nome = "Outros",
                            Tipo = 1
                        },
                        new
                        {
                            Id = new Guid("aaaaaaaa-aaaa-aaaa-aaaa-aaaaaaaaaaaa"),
                            Ativo = true,
                            CorHexadecimal = "#51CF66",
                            DataCriacao = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Descricao = "Salário mensal, décimo terceiro",
                            EhPadrao = true,
                            Icone = "fa-money-bill-wave",
                            Nome = "Salário",
                            Tipo = 2
                        },
                        new
                        {
                            Id = new Guid("bbbbbbbb-bbbb-bbbb-bbbb-bbbbbbbbbbbb"),
                            Ativo = true,
                            CorHexadecimal = "#339AF0",
                            DataCriacao = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Descricao = "Trabalhos autônomos, freelas",
                            EhPadrao = true,
                            Icone = "fa-laptop-code",
                            Nome = "Freelance",
                            Tipo = 2
                        },
                        new
                        {
                            Id = new Guid("cccccccc-cccc-cccc-cccc-cccccccccccc"),
                            Ativo = true,
                            CorHexadecimal = "#FF6B6B",
                            DataCriacao = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Descricao = "Dividendos, rendimentos, ações",
                            EhPadrao = true,
                            Icone = "fa-chart-line",
                            Nome = "Investimentos",
                            Tipo = 2
                        },
                        new
                        {
                            Id = new Guid("dddddddd-dddd-dddd-dddd-dddddddddddd"),
                            Ativo = true,
                            CorHexadecimal = "#FFD43B",
                            DataCriacao = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Descricao = "Vendas de produtos ou serviços",
                            EhPadrao = true,
                            Icone = "fa-shopping-cart",
                            Nome = "Vendas",
                            Tipo = 2
                        },
                        new
                        {
                            Id = new Guid("eeeeeeee-eeee-eeee-eeee-eeeeeeeeeeee"),
                            Ativo = true,
                            CorHexadecimal = "#6C757D",
                            DataCriacao = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Descricao = "Receitas diversas",
                            EhPadrao = true,
                            Icone = "fa-plus-circle",
                            Nome = "Outros",
                            Tipo = 2
                        });
                });

            modelBuilder.Entity("Organizzae.Domain.Entities.Despesa", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("AnexoComprovante")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<bool>("Ativo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<Guid>("CategoriaId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("DataAtualizacao")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DataCriacao")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DataPagamento")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DataVencimento")
                        .HasColumnType("datetime2");

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int?>("FormaPagamento")
                        .HasColumnType("int");

                    b.Property<string>("Observacoes")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<int>("TipoRecorrencia")
                        .HasColumnType("int");

                    b.Property<Guid>("UsuarioId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal>("Valor")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("CategoriaId")
                        .HasDatabaseName("IX_Despesas_CategoriaId");

                    b.HasIndex("DataVencimento")
                        .HasDatabaseName("IX_Despesas_DataVencimento");

                    b.HasIndex("Status")
                        .HasDatabaseName("IX_Despesas_Status");

                    b.HasIndex("TipoRecorrencia")
                        .HasDatabaseName("IX_Despesas_TipoRecorrencia");

                    b.HasIndex("UsuarioId")
                        .HasDatabaseName("IX_Despesas_UsuarioId");

                    b.HasIndex("UsuarioId", "DataVencimento")
                        .HasDatabaseName("IX_Despesas_UsuarioId_DataVencimento");

                    b.ToTable("Despesas", (string)null);
                });

            modelBuilder.Entity("Organizzae.Domain.Entities.Objetivo", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("Ativo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<DateTime>("DataAlvo")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DataAtualizacao")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DataConclusao")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DataCriacao")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DataInicio")
                        .HasColumnType("datetime2");

                    b.Property<string>("Descricao")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("ImagemRepresentativa")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<Guid>("UsuarioId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal>("ValorEconomizado")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("ValorTotal")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("DataAlvo")
                        .HasDatabaseName("IX_Objetivos_DataAlvo");

                    b.HasIndex("Status")
                        .HasDatabaseName("IX_Objetivos_Status");

                    b.HasIndex("UsuarioId")
                        .HasDatabaseName("IX_Objetivos_UsuarioId");

                    b.HasIndex("UsuarioId", "Status")
                        .HasDatabaseName("IX_Objetivos_UsuarioId_Status");

                    b.ToTable("Objetivos", (string)null);
                });

            modelBuilder.Entity("Organizzae.Domain.Entities.Receita", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("Ativo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<Guid>("CategoriaId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("DataAtualizacao")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DataCriacao")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DataPrevista")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DataRecebimento")
                        .HasColumnType("datetime2");

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Observacoes")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<int>("TipoRecorrencia")
                        .HasColumnType("int");

                    b.Property<Guid>("UsuarioId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal>("Valor")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("CategoriaId")
                        .HasDatabaseName("IX_Receitas_CategoriaId");

                    b.HasIndex("DataPrevista")
                        .HasDatabaseName("IX_Receitas_DataPrevista");

                    b.HasIndex("Status")
                        .HasDatabaseName("IX_Receitas_Status");

                    b.HasIndex("TipoRecorrencia")
                        .HasDatabaseName("IX_Receitas_TipoRecorrencia");

                    b.HasIndex("UsuarioId")
                        .HasDatabaseName("IX_Receitas_UsuarioId");

                    b.HasIndex("UsuarioId", "DataPrevista")
                        .HasDatabaseName("IX_Receitas_UsuarioId_DataPrevista");

                    b.ToTable("Receitas", (string)null);
                });

            modelBuilder.Entity("Organizzae.Domain.Entities.Usuario", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("Ativo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<string>("CPF")
                        .IsRequired()
                        .HasMaxLength(11)
                        .HasColumnType("nvarchar(11)");

                    b.Property<DateTime?>("DataAtualizacao")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DataCriacao")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("FotoPerfil")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("SenhaHash")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<DateTime?>("UltimoAcesso")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("CPF")
                        .IsUnique()
                        .HasDatabaseName("IX_Usuarios_Cpf");

                    b.HasIndex("Email")
                        .IsUnique()
                        .HasDatabaseName("IX_Usuarios_Email");

                    b.ToTable("Usuarios", (string)null);
                });

            modelBuilder.Entity("Organizzae.Domain.Entities.Despesa", b =>
                {
                    b.HasOne("Organizzae.Domain.Entities.Categoria", "Categoria")
                        .WithMany("Despesas")
                        .HasForeignKey("CategoriaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Organizzae.Domain.Entities.Usuario", "Usuario")
                        .WithMany("Despesas")
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Categoria");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("Organizzae.Domain.Entities.Objetivo", b =>
                {
                    b.HasOne("Organizzae.Domain.Entities.Usuario", "Usuario")
                        .WithMany("Objetivos")
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("Organizzae.Domain.Entities.Receita", b =>
                {
                    b.HasOne("Organizzae.Domain.Entities.Categoria", "Categoria")
                        .WithMany("Receitas")
                        .HasForeignKey("CategoriaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Organizzae.Domain.Entities.Usuario", "Usuario")
                        .WithMany("Receitas")
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Categoria");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("Organizzae.Domain.Entities.Categoria", b =>
                {
                    b.Navigation("Despesas");

                    b.Navigation("Receitas");
                });

            modelBuilder.Entity("Organizzae.Domain.Entities.Usuario", b =>
                {
                    b.Navigation("Despesas");

                    b.Navigation("Objetivos");

                    b.Navigation("Receitas");
                });
#pragma warning restore 612, 618
        }
    }
}
